name: Reviewdog

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  reviewdog:
    runs-on: ubuntu-latest

    if: |
      github.event_name == 'pull_request' ||
      (contains(github.event.comment.html_url, '/pull/') && startsWith(github.event.comment.body, '/reviewdog'))

    steps:

    - name: Checkout
      if: github.event_name == 'pull_request'
      uses: actions/checkout@v2

    - name: Checkout on issue_comment
      if: github.event_name == 'issue_comment'
      run: hub pr checkout ${{ github.event.issue.number }}

    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install
      run: |
        python -m pip install -U pip
        pip install --progress-bar off -U .[checking]

    - name: Black
      run: |
        black .
        blackdoc .
        isort .

    - name: Reviewdog
      uses: reviewdog/action-suggester@v1
      with:
        tool_name: formatters
